Source code/QuanLyBanDungCuHocTap24/WebBanDungCuHocTap/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanDungCuHocTap.Models;
namespace WebBanDungCuHocTap.Controllers
{
    public class CartController : Controller
    {
        Db_WebBanDungCuHocTap da = new Db_WebBanDungCuHocTap();

        // GET: Cart of current customer
        public ActionResult getCart(int customerID)
        {
            var cart = da.Carts.FirstOrDefault(s => s.CustomerID == customerID);

            if(cart != null)
            {
                var cartDetails = da.Cart_Details.Where(cd => cd.CartID == cart.CartID);
                return View(cartDetails);
            }
            return View();
        }

        //add product into cart

        [HttpPost]
        public ActionResult addtoCart(int productID, int customerID, int quantity, string type = "normal")
        {

            //Nếu đã đăng nhập mới được thêm vào
            if (Session["User"] != null)
            {
                //Thêm vào CSDL
                try
                {
                    //Tìm xem khách hàng này đã có Cart chưa
                    var cart = da.Carts.FirstOrDefault(s => s.CustomerID == customerID);

                    //chưa tạo cart trước đó => tạo Cart
                    if(cart == null)
                    {

                        Cart newCart = new Cart()
                        {
                            CustomerID = customerID,
                        };

                        da.Carts.Add(newCart);
                        da.SaveChanges();
                    }

                    //Tạo Order Details: thêm CartID, ProductID, Quantity, UnitPrice
                    int cartID = da.Carts.FirstOrDefault(s => s.CustomerID == customerID).CartID;

                    decimal unitPrice = (decimal)da.Products.FirstOrDefault(s => s.ProductID == productID).UnitPrice;

                    //Xem coi sản phẩm đó có tồn tại trong cart của khách hàng hiện tại hay chưa
                    var cartDetails = da.Cart_Details.FirstOrDefault(s => s.CartID == cartID && s.ProductID == productID);
                    //1. Nếu chưa thì thêm
                    if(cartDetails == null)
                    {
                        Cart_Detail newCartDetail = new Cart_Detail()
                        {
                            CartID = cartID,
                            ProductID = productID,
                            Quantity = (short?)quantity,
                            UnitPrice = unitPrice
                        };

                        da.Cart_Details.Add(newCartDetail);
                    }
                    else //2. Nếu có rồi thì cộng vào số lượng
                    {
                        cartDetails.CartID = cartID;
                        cartDetails.ProductID = productID;
                        cartDetails.Quantity += (short?)quantity;
                        cartDetails.UnitPrice = unitPrice;
                    }
                    da.SaveChanges();

                    if(type == "ajax")
                    {
                        return Json(new {
                            productID, 
                            customerID,
                            quantity,
                            soLuong = da.Cart_Details.Count(s => s.CartID == cartID),
                            totalPrice = da.Cart_Details.Where(s => s.CartID == cartID).Sum(s => s.UnitPrice * s.Quantity)
                        });
                    }

                }
                catch (Exception e)
                {
                    throw e;
                }
            }
            return RedirectToAction("../Home/Index");
        }
    
        public ActionResult deleteCart(int productID, int customerID, string type = "ajax")
        {
            var cart = da.Carts.FirstOrDefault(s => s.CustomerID == customerID);

            var cartDetailsToDelete = da.Cart_Details.FirstOrDefault(s => s.CartID == cart.CartID && s.ProductID == productID);

            da.Cart_Details.Remove(cartDetailsToDelete);

            da.SaveChanges();

            if (type == "ajax")
            {
                return Json(new
                {
                    productID,
                    customerID,
                    soLuong = da.Cart_Details.Count(s => s.CartID == cart.CartID),
                    totalPrice = da.Cart_Details.Where(s => s.CartID == cart.CartID).Sum(s => s.UnitPrice * s.Quantity)
                });
            }

            return RedirectToAction("../Home/Index");


        }


    }
}

Source code/QuanLyBanDungCuHocTap24/WebBanDungCuHocTap/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanDungCuHocTap.Models;

namespace WebBanDungCuHocTap.Controllers
{
    public class OrderController : Controller
    {
        Db_WebBanDungCuHocTap da = new Db_WebBanDungCuHocTap();

        public ActionResult getOrder(int customerID)
        {
            var order = da.Orders.Where(s => s.CustomerID == customerID);

            return View(order);
        }

        public ActionResult getOrderToCheckOut(int customerID)
        {
            var cart = da.Carts.FirstOrDefault(s => s.CustomerID == customerID);

            if (cart != null)
            {
                var cartDetails = da.Cart_Details.Where(cd => cd.CartID == cart.CartID);
                return View(cartDetails);
            }
            return View();
        }

        [HttpPost]
        public ActionResult addToOrder(
            int customerID,
            string shipAddress,
            string shipCity,
            string shipCountry,
            List<int> productValues,
            List<int> quantityValues,
            List<double> unitPriceValues
            )
        {
            try
            {

            //Thêm vào bảng Order
            using (var transaction = da.Database.BeginTransaction())
            {
                try
                {
                    Order order = new Order()
                    {
                        CustomerID = customerID,
                        EmployeeID = 1,
                        OrderDate = DateTime.Now,
                        ShippedDate = DateTime.Now.AddDays(3),
                        ShipAddress = shipAddress,
                        ShipCity = shipCity,
                        ShipCountry = shipCountry,
                    };
                    da.Orders.Add(order);
                    da.SaveChanges();

                    transaction.Commit();
                }
                catch (Exception e)
                {
                    transaction.Rollback();
                    throw e;
                }
            }

            //Thêm vào bảng Order Details

            using (var transaction = da.Database.BeginTransaction())
            {
                try
                {
                    int orderID = da.Orders.OrderByDescending(s => s.OrderID).FirstOrDefault().OrderID;

                    int length = productValues.Count();

                    for (int i = 0; i < length; ++i)
                    {
                        int OrderID = orderID;
                        int ProductID = productValues[i];
                        decimal? UnitPrice = (decimal?)unitPriceValues[i];
                        short? Quantity = (short?)quantityValues[i];

                        Order_Detail orderDetail = new Order_Detail()
                        {
                            OrderID = OrderID,
                            ProductID = ProductID,
                            UnitPrice = UnitPrice,
                            Quantity = Quantity
                        };

                        da.Order_Details.Add(orderDetail);
                    }

                    da.SaveChanges();
                    transaction.Commit();

                }
                catch (Exception e)
                {
                    transaction.Rollback();
                    throw e;
                }
            }

            //Xóa toàn bộ sản phẩm hiện tại của khách hàng ở trong Cart

            var cartsToDelete = da.Carts.Where(s => s.CustomerID == customerID);
            da.Carts.RemoveRange(cartsToDelete);


            da.SaveChanges();

            return View();
            }

            catch (Exception e)
            {
                throw e;
            }
        }
    }
}

Source code/QuanLyBanDungCuHocTap24/WebBanDungCuHocTap/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanDungCuHocTap.Models;
using PagedList;

namespace WebBanDungCuHocTap.Controllers
{
    public class ProductController : Controller
    {
        Db_WebBanDungCuHocTap da = new Db_WebBanDungCuHocTap();

        //Lấy danh sách sản phẩm dựa trên categoryID
        public ActionResult getCategories(int id, int page = 1)
        {
            //to get list of categories
            ViewBag.listCategories = da.Categories.Select(s => s);


            //to get list of products based on CategoryID
            try
            { 
                page = page < 1 ? 1 : page;

                int pageSize = 9;

                var list = da.Products
                .Where(s => s.CategoryID == id) // Lọc theo CategoryID
                .OrderBy(s => s.ProductID)
                .ToPagedList(page, pageSize);
                return View(list);


            }
            catch (Exception e)
            {
                throw e;
            }
            return View();


        }

        //Lấy sản phẩm dựa trên productID
        public ActionResult getProduct(int id)
        {
            ViewBag.listCategories = da.Categories.Select(s => s);

            var p = da.Products.FirstOrDefault(s => s.ProductID == id);

            return View(p);
        }
    }
}

Source code/QuanLyBanDungCuHocTap24/WebBanDungCuHocTap/Views/Shared/Hero.cshtml
<!-- Hero Section Begin -->
<section class="hero">
    <div class="container">
        <div class="row">
            
            <div class="col-lg-9">
                <div class="hero__search">
                    <div class="hero__search__form">
                        <form action="#">
                            <input type="text" placeholder="What do you need?">
                            <button type="submit" class="site-btn">SEARCH</button>
                        </form>
                    </div>
                    <div class="hero__search__phone">
                        <div class="hero__search__phone__icon">
                            <i class="fa fa-phone"></i>
                        </div>
                        <div class="hero__search__phone__text">
                            <h5>+65 11.188.888</h5>
                            <span>support 24/7 time</span>
                        </div>
                    </div>
                </div>
                <div>
                    <img class="hero__item img-100" src="~/Content/img/banner/Deli_banner.png">
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Hero Section End -->

Source code/QuanLyBanDungCuHocTap24/WebBanDungCuHocTap/Views/Shared/Search.cshtml
<div class="col-lg-9">
    <div class="hero__search">
        <div class="hero__search__form">
            <form action="#">
                <input type="text" placeholder="What do you need?">
                <button type="submit" class="site-btn">SEARCH</button>
            </form>
        </div>
        <div class="hero__search__phone">
            <div class="hero__search__phone__icon">
                <i class="fa fa-phone"></i>
            </div>
            <div class="hero__search__phone__text">
                <h5>+65 11.188.888</h5>
                <span>support 24/7 time</span>
            </div>
        </div>
    </div>
    <div>
        <img class="hero__item img-100" src="~/Content/img/banner/Deli_banner.png">
    </div>
</div>

Source code/QuanLyBanDungCuHocTap24/WebBanDungCuHocTap/Views/Shared/Slide.cshtml
<div class="col-lg-3">
    <div class="hero__categories">
        <div class="hero__categories__all">
            <i class="fa fa-bars"></i>
            <span>Danh mục sản phẩm</span>
        </div>
        <ul>
            @foreach (var item in @ViewBag.listCategories)
            {
                <li><a href="@Url.Action("getCategories", "Product", new { id = item.CategoryID })"><i class="fa fa-circle"></i>@item.CategoryName</a></li>
            }
        </ul>
    </div>
</div>

Source code/QuanLyBanDungCuHocTap24/WebBanDungCuHocTap/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Công ty TNHH ABC Việt Nam">
    <meta name="keywords" content="html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Công ty TNHH ABC Việt Nam</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/elegant-icons.css" rel="stylesheet" />
    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/css/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/css/nice-select.css" rel="stylesheet" />
    <link href="~/Content/css/slicknav.min.css" rel="stylesheet" />

    <link href="~/Content/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/Content/css/owl.theme.default.min.css" rel="stylesheet" />

    <link href="~/Content/css/style.css" rel="stylesheet" media="screen" runat="server" />

    <link href="~/Content/css/Notification.css" rel="stylesheet" media="screen" runat="server" />

</head>

<body>
    @{ var user = Session["User"] as WebBanDungCuHocTap.Models.Customer; }
    @using WebBanDungCuHocTap.Models;
    @{
        Db_WebBanDungCuHocTap da = new Db_WebBanDungCuHocTap();

    }

    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__left">
                            <ul>
                                <li><i class="fa fa-envelope"></i> 2054052054tai@ou.edu.vn</li>
                                <li>Free Shipping for all Order of $99</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__right">
                            <div class="header__top__right__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                <a href="#"><i class="fa fa-pinterest-p"></i></a>
                            </div>
                            @{ if (user == null)
                                {
                                    <div class="header__top__right__auth">
                                        <a href="/Account/Login"><i class="fa fa-user"></i> Login</a>
                                        <a href="/Account/Register"><i class="fa fa-user-plus"></i> Sign up</a>
                                    </div>
                                }
                                if (user != null)
                                {
                                    <div class="header__top__right__auth">
                                        <p class="userName">Hello: @user.UserName</p>
                                        <a href="@Url.Action("getOrder", "Order", new { customerID = user.CustomerID })"><i class="fa fa-truck"></i> Đơn mua</a>

                                        <a href="/Account/Logout"><i class="fa fa-user-plus"></i> Log out</a>
                                    </div>
                                }
                            }

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="/Home/Index"><img class="img-50" src="~/Content/img/logo/Deli_logo.png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a href="/Home/Index">Home</a></li>
                            <li><a href="/Home/Index">Shop</a></li>
                            <li><a href="./shop-grid.html">Sales policy</a></li>
                            <li><a href="./shop-grid.html">Contact</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3">
                    @{if (user != null)
                        {
                            <div class="header__cart">
                                <ul>
                                    <li>
                                        <a href="@Url.Action("getCart", "Cart", new { customerID = user.CustomerID })">


                                            <i class="fa fa-shopping-bag"></i>
                                            <span id="cart-count">
                                                @{
                                                    int cartID = -1;
                                                    int SoLuong = 0;
                                                    var check = da.Carts.FirstOrDefault(s => s.CustomerID == user.CustomerID);
                                                    if (check != null)
                                                    {
                                                        cartID = da.Carts.FirstOrDefault(s => s.CustomerID == user.CustomerID).CartID;
                                                        SoLuong = da.Cart_Details.Count(s => s.CartID == cartID);
                                                    }
                                                    @SoLuong
                                                }


                                            </span>
                                        </a>
                                    </li>
                                </ul>

                                @*Tổng giá trị của giỏ hàng*@
                                <div class="header__cart__price">
                                    item: $
                                    <span id="cart-total-price">
                                        @{
                                            if (check != null)
                                            {
                                                var totalPrice = da.Cart_Details.Where(s => s.CartID == cartID).Sum(s => s.UnitPrice * s.Quantity);
                                                @String.Format("{0:0.00}", totalPrice)
                                            }
                                            else
                                            {
                                                @String.Format("{0:0.00}", 0)

                                            }

                                        }
                                    </span>
                                </div>
                            </div>
                        }
                    }

                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->

    @RenderBody()

    <!-- Footer Section Begin -->
    <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__about__logo">
                            <a href="./index.html"><img src="img/logo.png" alt=""></a>
                        </div>
                        <ul>
                            <li>Address:371 Nguyễn Kiệm</li>
                            <li>Phone: +65 11.188.888</li>
                            <li>Email: 2054052054tai@ou.edu.vn</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                    <div class="footer__widget">
                        <h6>Useful Links</h6>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">About Our Shop</a></li>
                            <li><a href="#">Secure Shopping</a></li>
                            <li><a href="#">Delivery infomation</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Our Sitemap</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">Who We Are</a></li>
                            <li><a href="#">Our Services</a></li>
                            <li><a href="#">Projects</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Innovation</a></li>
                            <li><a href="#">Testimonials</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="footer__widget">
                        <h6>Join Our Newsletter Now</h6>
                        <p>Get E-mail updates about our latest shop and special offers.</p>
                        <form action="#">
                            <input type="text" placeholder="Enter your mail">
                            <button type="submit" class="site-btn">Subscribe</button>
                        </form>
                        <div class="footer__widget__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer__copyright">
                        <div class="footer__copyright__text">
                            <p>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Tài</a>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                        <div class="footer__copyright__payment"><img src="img/payment-item.png" alt=""></div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->
    <!-- Js Plugins -->
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/jquery-3.3.1.min.js"></script>
    <script src="~/Content/js/jquery-ui.min.js"></script>
    <script src="~/Content/js/jquery.nice-select.min.js"></script>
    <script src="~/Content/js/jquery.slicknav.js"></script>
    <script src="~/Content/js/main.js"></script>
    <script src="~/Content/js/mixitup.min.js"></script>
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <script src="jquery.min.js"></script>
    <script src="owlcarousel/owl.carousel.min.js"></script>

    <script src="~/Content/js/Notification.js"></script>
    <script>
        $('.owl-carousel').owlCarousel({
            loop: true,
            margin: 10,
            autoplay: true,
            autoplayTimeout: 3000,
            autoplayHoverPause: true,
            nav: true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 3
                },
                1000: {
                    items: 5
                }
            }
        })
    </script>


</body>

</html>